//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.DataPoints = new HashSet<DataPoint>();
            this.DeviceStates = new HashSet<DeviceState>();
            this.DeviceGroups = new HashSet<DeviceGroup>();
        }
    
        public string DeviceID { get; set; }
        public string Email { get; set; }
        public bool DevicePrivacy { get; set; }
    
        public virtual ICollection<DataPoint> DataPoints { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<DeviceState> DeviceStates { get; set; }
        public virtual ICollection<DeviceGroup> DeviceGroups { get; set; }
    }
}
