//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace server_api
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceState
    {
        public string DeviceID { get; set; }
        public System.DateTime StateTime { get; set; }
        public decimal Lat { get; set; }
        public decimal Long { get; set; }
        public bool InOrOut { get; set; }
        public bool StatePrivacy { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
